### ISSUE TITLE
Fix incorrect parsing of the `-executionTime` command-line parameter

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#102]
**TODO**:
- [x] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
