### ISSUE TITLE
Create a general class for managing command line parameters

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#105]
### **Description**
**Problem:**
Currently, RTI Perftest's input commands have to be parsed several times in different classes, some of the parameters are repeated in these classes, and accessing to some of them can be challenging.

**Solution:**
Create a new independent class where all the parameters are allocated.
It will define the parameter, parse them and validate them. It will also print the help. 
Everything in a flexible way.

**Deprecated parameter** 
The following parameters will be deprecated:
- fastHeartbeatPeriod
- keepDurationUsec

The following will be kept as internal:
- instanceHashBuckets
-  spin
- heartbeatPeriod

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review](https://github.com/rticommunity/rtiperftest/pull/106)
- [ ] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review](https://github.com/rticommunity/rtiperftest/pull/106)
- [ ] Final Merge into master
