### ISSUE TITLE
Remove a unnecessary TODO in java

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#109]
**Description**
In rtiperftest/srcJava/com/rti/perftest/harness/LatencyListener.java:205

```
// TODO: This std dev calculation isn't correct!
double latency_std = sqrt(
        abs(_latencySumSquare / (double)_count -
                (latency_ave * latency_ave)));
```
**The formula is correct and the TODO is not needed.**

**TODO**:
- [x] Support for Java
- [x] Full [Code Review]()
- [ ] Final Merge into master
