### ISSUE TITLE
Logic error on RTIDynamicDataSubscriber constructor.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#111]
**Description**

In rtiperftest/srcCpp/RTIDDSImpl.cxx:1684.
Possible call to NULL pointer.

`
    RTIDynamicDataSubscriber(DDSDataReader *reader): _message()
    {
        _reader = DDSDynamicDataReader::narrow(reader); //fail -> _reader = NULL
        if (_reader == NULL) {
            fprintf(stderr,"DDSDynamicDataReader::narrow(reader) error.\n");
           // throw runtime_error exception
        }
        _data_idx = 0;
        _no_data = false;

        // null listener means using receive thread
        if (_reader->get_listener() == NULL) { //Call to NULL pointer FAIL
            ...
            ...
        }
    }
`
If  DDSDynamicDataReader::narrow(reader) fail, and return NULL, a call to NULL pointer will be done for _reader->get_listener() where _reader will be NULL.

**Expected behavior**

A exception should be throw if  `_reader == NULL` after call `narrow(reader)`

**TODO**:
- [x] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
