### ISSUE TITLE
Use operator [] in function DynamicDataMembersId::at()

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#114]
**Description**
Currently we are using 
```
 int DynamicDataMembersId::at(std::string key)
 {
    return membersId.at(key);
}
```
It is generating problem in VxWorks, becuause at() method is only for C++11
The way how to solve:
```
 int DynamicDataMembersId::at(std::string key)
 {
    return membersId[key];
}
```

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Support for C++ Modern
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
