### ISSUE TITLE
Issue running Vxworks

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#120]
**Description**
Error publisher:
```
Finishing test...
0xffff800001e3b9b0 (tShellRem18446603336252888512): memPartFree: invalid block 0xffff8000001e7960 in partition 0xffffffff806f0140
Test ended.
```
Error subscriber:
```
Length:   100  Latency: Ave   2972 us  Std   40.1 us  Min   2944 us  Max   3369 us  50%   2966 us  90%   2983 us  99%   3084 us  99.99%   3369 us  99.9999%   3369 us 
Finishing test...
DDS_DomainParticipantFactory_deleteI:!delete factory instance: outstanding participant(s)
DDSDomainParticipantFactory::delete_instanceI:!delete participant factory
DDSDomainParticipantFactory::finalize_instance:!delete participant factory
Test ended.
value = 0 = 0x0
-> 0xffff800001e3b9b0 (tShellRem18446603336252888512): memPartFree: invalid block 0xffff8000001e7960 in partition 0xffffffff806f0140
```
**How to Reproduce**
Running in vxworks6.9

**TODO**:
- [X] Support for C++ Traditional
- [X] First CR [Code Review]()
- [X] Support for C++ Modern
- [X] Automatic install testing
- [X] Documentation
- [X] Full [Code Review]()
- [X] Final Merge into master

**Comment by salvacorts** [comment]
**Should we need to fix it?**
Again the problem is that in VxWorks, static objects are shared across instances of the program within the same machine. This message occurs when `DDSDomainParticipantFactory::finalize_instance();` is called in *RTIDDSImpl.cxx*; Even though we have deleted our participants previously (a couple of lines above), the participants from other instances of *perftest* in the same machine are still there.

This is not actually a problem since the last instance of perftest to finish will delete the last participant of *DDSDomainParticipantFactory* and will call  `DDSDomainParticipantFactory::finalize_instance();` successfully.

We can omit this message by iterating through all the participants in *DDSDomainParticipantFactory* by calling `DDSDomainParticipantFactory::get_participants(DDSDomainParticipantSeq & participants)`, before calling `DDSDomainParticipantFactory::finalize_instance()`, and then for each participant, delete its contained entinies and deleting it from *DDSDomainParticipantFactory*.

The problem I see in this approach is that we will be potentially deleting participants that are still on use in other instances of *perftest* in the same machine (e.g. scenario with two publishers with two different timers and one subscriber).

**Comment by salvacorts** [comment]
It is fixed it. Now it displays a message instead: `[Warning] Cannot finalize Domain Factory since it is being in use by another thread(s)`
![image](https://user-images.githubusercontent.com/8354290/58414136-cc17fb80-807a-11e9-8446-bca98a118815.png)
