### ISSUE TITLE
Error using -unbounded option.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#121]
**Description**
Error using -unbounded option.

**How to Reproduce**
Command: ``` perftest_cpp -sub -domain 19 -unbounded ```
```
RTI Perftest 2.3.2 (RTI Connext DDS 5.3.1)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Subscriber ID: 0
	Receive using: Listeners
	Domain: 19
	Dynamic Data: No
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4 & SHMEM (taken from QoS XML file)
	Use Multicast: False

REDAFastBufferPool_growEmptyPoolEA: !allocate buffer of 214748263200 bytes

REDAFastBufferPool_newWithNotification:!create fast buffer pool buffers

PRESTypePluginDefaultEndpointData_createWriterPool:!create writer buffer pool

PRESPsService_enableLocalEndpointWithCursor:failed to attach endpoint to typePlugin

PRESPsService_enableLocalEndpoint:!enable local endpoint

DDSDataWriter_impl::createI:ERROR: Failed to auto-enable entity

Problem creating writer.
Problem creating latency writer.
Test ended.


```

**Expected behavior**

Not fail.

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
