### ISSUE TITLE
Custom Type failed in OSX

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#125]
**Description**
Error: 
```
RTIDDSImpl.cxx:1563:17: error: '(anonymous struct at RTIDDSImpl.cxx:1560:9)' cannot be defined in a type specifier
                RTIOsapiAlignment_getAlignmentOf(char *));
                ^
/Users/jmorales/RTI/trees/connextdds/ndds.4.1/include/ndds/osapi/osapi_alignment_impl.h:72:15: note: expanded from macro 'RTIOsapiAlignment_getAlignmentOf'
    offsetof (struct { char c; testType member; }, member)
              ^
1 error generated.
make: *** [objs/x64Darwin16clang8.0/RTIDDSImpl.o] Error 1
[ERROR]: Failure compiling code for C++.
```
**How to Reproduce**
./build.sh --platform x64Darwin16clang8.0 --nddshome /local/preship/ndds/ndds.5.3.1/unlicensed/rti_connext_dds-5.3.1 --cpp-build --customType Test

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Full [Code Review]()
- [ ] Final Merge into master
