### ISSUE TITLE
Perftest Version and DDS version appear at the end of he test for C++98

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#131]
**Description**

For c++, the Version of DDS and perftest is been flushing at the end of the test. 

```
[...]
Publishing data ...
Setting timeout to 60 seconds
RTI Perftest 2.3.2 (RTI Connext DDS 5.3.1)
Length:    32  Latency: Ave    386 us  Std   47.4 us  Min    357 us  Max    674 us  50%    380 us  90%    390 us  99%    674 us  99.99%    674 us  99.9999%    674 us 
Finishing test...
```
**How to Reproduce**
Execute a test on C++

**Expected Behaviour**

This line should be printed the first one when the test is launch.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Full [Code Review]()
- [ ] Final Merge into master
