### ISSUE TITLE
Migrate RTI Routing Service XML configuration to 6.0.0

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#140]
**Description**

Migrate RTI Routing Service XML configuration to 6.0.0

**TODO**:
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
