### ISSUE TITLE
Support Recording Service in RTI Perftest

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#145]
**Description**
Measure the performance of Recording Service using RTI Perftest.

**TODO**:
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
