### ISSUE TITLE
Unify the QoS, script and documentation section of Routing Service with Recording Service

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#147]
**Description**

Recording service and Routing service will share:
- QoS
- Script
- Documentation section.

**TODO**:
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
