### ISSUE TITLE
Fix for low precision clock latency measurements

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#162]
**Description**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master
