### ISSUE TITLE
Use of 

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#163]
**Description**

**How to Reproduce**

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
