### ISSUE TITLE
Use of "Alarm" deprecated/not supported in several architectures

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#164]
**Description**

`Alarm` is used in this context:

```
void PerftestTimer::setTimeout(
        unsigned int executionTimeInSeconds,
        void (*function)(void))
{

    _handlerFunction = function;

  #ifdef RTI_WIN32
    CreateTimerQueueTimer(
            &_hTimer,
            _hTimerQueue,
            (WAITORTIMERCALLBACK)PerftestTimer::timeoutTask,
            NULL,
            executionTimeInSeconds * 1000,
            0,
            0);
  #else
    signal(SIGALRM, PerftestTimer::timeoutTask);
    alarm(executionTimeInSeconds);
  #endif
}
```

**How to Reproduce**

**Expected behavior**

**TODO**:
- [X] Support for C++ Traditional
- [X] First CR [Code Review]()
- [X] Support for C++ Modern
- [X] Documentation
- [X] Full [Code Review]()
- [X] Final Merge into master
