### ISSUE TITLE
In certain VxWorks when using publisher and subscriber in the same machine the -noPrint parameter is shared

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#166]
**Description**

In certain VxWorks when using publisher and subscriber in the same machine the -noPrint parameter is shared

**How to Reproduce**

**Expected behavior**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
