### ISSUE TITLE
Provide a way to run RTI Perftest easier in VxWorks

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#167]
**Description**

Provide a way to easily run RTI Perftest in VxWorks by calling a function which receives a simple `std::string` containing all the command line parameters.

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master

**Comment by salvacorts** [comment]
I will proceed to close this issue since now the PR #171 has been merged into master.
