### ISSUE TITLE
build.sh still tries to build cpp/03 when make/compiler/linker not found

### ISSUE THREAD

**Issue by KyleBenson** [rticommunity/rtiperftest#169]
**Description**

If you specify the *GNU make*, compiler, or linker executable to be an executable that bash cannot find, build.sh will claim that perftest_cpp and/or perftest_cpp03 will not be built. However, it will still try to build them and then fail when the command is not found.

**How to Reproduce**

``./build.sh --make blahblah --platform $YOUR_ARCH``

**Expected behavior**

build.sh should not try to build targets that it claims will not be built.

**TODO**:
- [x] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [x] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
Fixed
