### ISSUE TITLE
Use global variable for announcement sleeping period. Change milliSleep to Sleep.

### ISSUE THREAD

**Issue by salvacorts** [rticommunity/rtiperftest#180]
**Description**
We are using `PerftestClock::milliSleep()` in several functions within _perftest;_ many of them are sleeping for the same amount of seconds so in case we want to change that value we will have to go one by one changing that value. Instead, we will use a global variable to store that value.

Finally we will use `NDDSUtility::sleep()` regardless of the operative system to implement `PerftestClock::milliSleep()`

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [x] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [ ] Final Merge into master
