### ISSUE TITLE
support_for_android

### ISSUE THREAD

**Issue by sarath-rti** [rticommunity/rtiperftest#186]
**Description**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [ ] Support for Java
- [ ] Support for CS
- [x] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master

**Comment by javmorcas** [comment]
@sarath-rti, let me know once you have the changes and I will include them for the 3.0.0 release (if it is not too late).

**Comment by javmorcas** [comment]
CS and Java will not be supported, Modern C++ can be built, but when setting Android as the platform we will only build Classic C++.
