### ISSUE TITLE
Invalid calculation on getTimeUsec() and a lack of precision on the Micro Clock implementation for windows could produce an incorrect latency results.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#201]
**Description**

In `PerftestClock::getTimeUsec()`  the following calculation results in a integer when the value is bigger than 4 bytes.
```return clockUsec + 1000000 * clockSec;```

This should be changed to:
```return clockUsec + (unsigned long long)1000000 * clockSec;```

This should not affect a Little-endian machine but for a big-endian, this will produce incorrect values.

On the other hand, the precision of the timestamp returned by Micro Clock has a milliseconds precision, not enough for a latency Test were usually the results are measured in the microseconds range.

**How to Reproduce**

Run a latency test on a Perftest for Micro in Windows, some of the one-way latency values from the publisher will be zero.

**Expected behavior**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
