### ISSUE TITLE
Issues in testing serialization/deserialization in 6.0.0

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#208]
**Description**

```
DDS_OctetSeq_set_member_element_count:ERROR: Failed to set sequence maximum
RTIXCdrInterpreter_fastDeserializeSample:TestDataLarge_t:bin_data deserialization error
Fail to deserialize sample on obtain_dds_deserialize_time_cost
DDS_OctetSeq_set_maximum:!assert buffer must not be loaned
DDS_OctetSeq_set_member_element_count:ERROR: Failed to set sequence maximum
RTIXCdrInterpreter_fastDeserializeSample:TestDataLarge_t:bin_data deserialization error
Fail to deserialize sample on obtain_dds_deserialize_time_cost
DDS_OctetSeq_set_maximum:!assert buffer must not be loaned
DDS_OctetSeq_set_member_element_count:ERROR: Failed to set sequence maximum
RTIXCdrInterpreter_fastDeserializeSample:TestDataLarge_t:bin_data deserialization error
Fail to deserialize sample on obtain_dds_deserialize_time_cost
DDS_OctetSeq_set_maximum:!assert buffer must not be loaned
DDS_OctetSeq_set_member_element_count:ERROR: Failed to set sequence maximum
RTIXCdrInterpreter_fastDeserializeSample:TestDataLarge_t:bin_data deserialization error
Fail to deserialize sample on obtain_dds_deserialize_time_cost
DDS_OctetSeq_set_maximum:!assert buffer must not be loaned
DDS_OctetSeq_set_member_element_count:ERROR: Failed to set sequence maximum
RTIXCdrInterpreter_fastDeserializeSample:TestDataLarge_t:bin_data deserialization error
Fail to deserialize sample on obtain_dds_deserialize_time_cost
```

**TODO**:
- [x] Support for C++ Traditional
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master
