### ISSUE TITLE
Support Flat Data and Zero Copy

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#211]
**Description**

**TODO**:
- [x] Support for C++ Traditional
- [x] Support for C++ Modern
- [x] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master
