### ISSUE TITLE
Large Data not working for C++ Implementation after Flat Data changes

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#214]
**Description**

```
jmorales@rocinante:~/RTI/trees/rtiperftest$ bin/x64Darwin17clang9.0/release/perftest_cpp -pub -transport UDPv4 -nic 127.0.0.1 -datalen 25000000 -domain 115 -noPrint -exec 10
RTI Perftest Master 1f2411f (RTI Connext DDS 6.0.0)
Large Data type

Mode: THROUGHPUT TEST
      (Use "-latencyTest" for Latency Mode)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Publisher ID: 0
	Latency count: 1 latency sample every 10000 samples
	Data Size: 25000000
	Batching: Disabled by RTI Perftest.
		  BatchSize cannot be used with
		  Large Data.
	Publication Rate: Unlimited (Not set)
	Execution time: 10 seconds
	Receive using: Listeners
	Domain: 115
	Dynamic Data: No
	FlatData: No
	Zero Copy: No
	Asynchronous Publishing: Yes
	Flow Controller: default
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Nic: 127.0.0.1
	Use Multicast: False

Waiting to discover 1 subscribers ...
Waiting for subscribers announcement ...
Sending 50 initialization pings ...
Publishing data ...
COMMENDSrWriterService_canSampleBeSent:!write. Reliable fragmented data requires asynchronous writer.
COMMENDSrWriterService_write:sample cannot be sent
PRESPsWriter_writeCommend:!srw->write
PRESPsWriter_writeInternal:!failed to write sample in Commend
COMMENDSrWriterService_canSampleBeSent:!write. Reliable fragmented data requires asynchronous writer.
COMMENDSrWriterService_write:sample cannot be sent
PRESPsWriter_writeCommend:!srw->write
PRESPsWriter_writeInternal:!failed to write sample in Commend
COMMENDSrWriterService_canSampleBeSent:!write. Reliable fragmented data requires asynchronous writer.
COMMENDSrWriterService_write:sample cannot be sent
```

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
The reason seems to be that we are using `isZeroCopy` in a path where it is not initialized:

```
    printf("_isLargeData -> %d\n", _isLargeData);
    printf("_isZeroCopy -> %d\n", _isZeroCopy);
    if ((_isLargeData && !_isZeroCopy) || _PM->get<bool>("asynchronous")) {
        printf("Setting asynchrnous\n");
```

The execution of this code:

```
jmorales@rocinante:~/RTI/trees/rtiperftest$ bin/x64Darwin17clang9.0/release/perftest_cpp -pub -transport UDPv4 -nic 127.0.0.1 -datalen 25000000 -domain 115 -noPrint -exec 10
RTI Perftest Master 1f2411f (RTI Connext DDS 6.0.0)
Large Data type

Mode: THROUGHPUT TEST
      (Use "-latencyTest" for Latency Mode)

Perftest Configuration:
	Reliability: Reliable
	Keyed: No
	Publisher ID: 0
	Latency count: 1 latency sample every 10000 samples
	Data Size: 25000000
	Batching: Disabled by RTI Perftest.
		  BatchSize cannot be used with
		  Large Data.
	Publication Rate: Unlimited (Not set)
	Execution time: 10 seconds
	Receive using: Listeners
	Domain: 115
	Dynamic Data: No
	FlatData: No
	Zero Copy: No
	Asynchronous Publishing: Yes
	Flow Controller: default
	XML File: perftest_qos_profiles.xml

Transport Configuration:
	Kind: UDPv4
	Nic: 127.0.0.1
	Use Multicast: False

_isLargeData -> 1
_isZeroCopy -> 112
Waiting to discover 1 subscribers
```

**Comment by javmorcas** [comment]
Fixed. I believe this also explains why we saw issues in the initial burst of samples @salvacorts.
