### ISSUE TITLE
Wrong capitalization for command line option "--customTypeFlatData"

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#232]
**Description**

From Howard: 

The command line option accepted is "--customTypeFlatdata" not "--customTypeFlatData", either the script is wrong or the documentation is.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Support for C++ Modern
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
