### ISSUE TITLE
Error using Micro with shmem when the test finalize

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#234]
**Description**
Two errors will come up at the end of a test using shmem on Micro:
```
[1571049872.218516000]ERROR: ModuleID=2 Errcode=15 X=1 E=0 T=1
db/DBUrtdb.c:1169/DB_Database_delete_table: table=rt

[1571049872.218609000]ERROR: ModuleID=3 Errcode=3 X=1 E=0 T=1
rt/RTRegistry.c:331/RT_Registry_finalize: dbrc=2

Test ended.
```

**How to Reproduce**
Launch the followings commands for a Perftest-Micro compilation:
Publisher:
```
$ ./bin/x64Linux4gcc7.3.0/debug/perftest_cpp_micro -pub -transport SHMEM -exec 2
```

Subscriber:
```
$ ./bin/x64Linux4gcc7.3.0/debug/perftest_cpp_micro -sub -transport SHMEM
```

**Expected behavior**
Any error should be triggered.

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
