### ISSUE TITLE
FlatData flags are enable to compile Rti Perftest with patched versions of rtiddsgen that does not support FlatData.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#237]
**Description**
The FlatData flags are used if the version of rtiddsgen is higher than 3.0.0. Due to the way that this is done, FlatData flags are enabled with a patched version of rtiddsgen as 2.4.1.27 that does not support FlatData.

**TODO**:
- [x] Changes for Shell systems
- [x] Changes for Batch systems
- [x] First CR [Code Review]()
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
