### ISSUE TITLE
Content filtering a range receives no samples by default

### ISSUE THREAD

**Issue by rgrti** [rticommunity/rtiperftest#240]
**Description**
When attempting to use -cft if you specify a range of IDs the subscriber will not receive any information without additional command line params
**How to Reproduce**
Using stock config files
pub side:
-pub -instances 10 -keyed
sub side:
-sub-keyed -cft 2:4

**Expected behavior**
sub should receive instances 2, 3, and 4
Single instance filtering like "-cft 4" will work
Or specifying -writeInstance 10 on the pub side will also force it to work

I would also recommend updating the documentation in 6.2.2.2
https://community.rti.com/static/documentation/perftest/3.0/examples.html#command-line-parameters
1: I was initially confused about the difference between -instances and -writeInstance, I recommend some clarification here that would help
2: I recommend mentioning you must use -keyed (this is probably obvious but I initially thought keyed instances would automatically be enabled if I specify -instances (maybe produce a warning if you don't use -keyed but you do use -cft or -instances to make it more obvious)

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [x] Automatic install testing
- [x] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
```    } else { // If cftRange.size() == 2 (RANGE)
        printf("CFT enabled for instance range: [%llu,%llu] \n",
                cftRange[0],
                cftRange[1]);
        char cft_param[2 * KEY_SIZE][128];
        for (unsigned int i = 0; i < 2 * KEY_SIZE ; i++ ) {
            printf(">>> INDEX %d\n", i);
            if (i < KEY_SIZE) {
                printf(">>> >>> %d --- ", (unsigned char)(cftRange[0]));
                printf("%d\n", (unsigned char)(cftRange[0] >> i * 8));
                sprintf(cft_param[i], "%d", (unsigned char)(cftRange[0] >> i * 8));
            } else { // KEY_SIZE < i < KEY_SIZE * 2
                printf(">>> >>> %d --- ", (unsigned char)(cftRange[1]));
                printf("%d\n", (unsigned char)(cftRange[1] >> i * 8));
                sprintf(cft_param[i], "%d", (unsigned char)(cftRange[1] >> i * 8));
            }
        }```


```
CFT enabled for instance range: [2,3] 
>>> INDEX 0
>>> >>> 2 --- 2
>>> INDEX 1
>>> >>> 2 --- 0
>>> INDEX 2
>>> >>> 2 --- 0
>>> INDEX 3
>>> >>> 2 --- 0
>>> INDEX 4
>>> >>> 3 --- 0
>>> INDEX 5
>>> >>> 3 --- 0
>>> INDEX 6
>>> >>> 3 --- 0
>>> INDEX 7
>>> >>> 3 --- 0
```

**Comment by javmorcas** [comment]
@rgrti, we found the issue, we will have the fix asap.
