### ISSUE TITLE
When ZeroCopy is used, Asynchronous Publishing is incorrectly printed as enable on the summary.

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#246]
This is shown even if ZeroCopy is used.

```
    Dynamic Data: No
    FlatData: Yes
    Zero Copy: Yes
    Asynchronous Publishing: Yes
    Flow Controller: default
    XML File: perftest_qos_profiles.xml
```

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [ ] Final Merge into master
