### ISSUE TITLE
ns resolution for perftest

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#253]
**Description**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
