### ISSUE TITLE
When using ns-resolution, modify latency variables to be unsigned long long

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#256]
**Description**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
