### ISSUE TITLE
Support for CRC on Micro

### ISSUE THREAD

**Issue by salvacorts** [rticommunity/rtiperftest#295]
**Description**
Micro 2.4.12.1 introduces support for CRC's of different lengths.
A user can decide whether to use the builtin CRC functions for 16, 32, and 64 bits or implement their own up to 128 bits.

Link to Jira issue: [MICRO-1131](https://jira.rti.com/browse/MICRO-1131)

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
