### ISSUE TITLE
Compilation failure in C++ and C++03 when trying to compile an architecture without flatData on Windows

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#319]
**Description**

On windows, rtiperftest will fail to build if flatData is not available in the architecture or if the Connext DDS version doesn't have FlatData.

This issue is triggered by the use of the following command in RTIDDSGEN:

```
call "C:\Program Files\rti_connext_dds-6.0.0/bin/rtiddsgen.bat" -language C++   -unboundedSupport -replace -create typefiles -create makefiles -platform x64Win64VS2015                -additionalHeaderFiles "RTIRawTransportImpl.h Parameter.h ParameterManager.h ThreadPriorities.h RTIDDSLoggerDevice.h MessagingIF.h RTIDDSImpl.h perftest_cpp.h qos_string.h CpuMonitor.h PerftestTransport.h Infrastructure_common.h Infrastructure_pro.h"    -additionalSourceFiles "RTIRawTransportImpl.cxx Parameter.cxx ParameterManager.cxx ThreadPriorities.cxx RTIDDSLoggerDevice.cxx RTIDDSImpl.cxx CpuMonitor.cxx PerftestTransport.cxx Infrastructure_common.cxx Infrastructure_pro.cxx"  -additionalDefines "/0x RTI_LANGUAGE_CPP_TRADITIONAL PERFTEST_COMMIT_ID=\"65792ca\""   -additionalRtiLibraries ""              -d "C:\rtiperftest\srcCpp" "C:\rtiperftest\srcIdl\perftest.idl"
```

In particular, the problem is this:

```
-additionalRtiLibraries ""
``` 

RTIDDSGEN will not be executed in this case, not generating anything.

**How to Reproduce**

Modify the section to enable FlatData and set it to false, or choose a ConnextDDS version prior to flatData.

This issue does not show up on Linux or MacOS.

**Expected behavior**

This should work, with the feature disabled.

**TODO**:
- [ ] Support for C++ Traditional
- [ ] Support for C++ Modern
- [ ] Documentation
- [ ] Full [Code Review]()
