### ISSUE TITLE
TSS Support

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#336]
**Description**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
