### ISSUE TITLE
The option -loadDataFromFile does not work for files bigger than 2Gb

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#341]
**Description**
All the variables that handle the size of an input file are integers types. The maximum integer value is 2147483647, that in bytes is 2Gb. If we try to use a file of 2Gb or bigger, we will end on a unexpected file size.

**How to Reproduce**

**Expected behavior**

**TODO**:
- [ ] Support for C++ Traditional
- [ ] First CR [Code Review]()
- [ ] Support for C++ Modern
- [ ] Automatic install testing
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master

**Comment by javmorcas** [comment]
@alfonso-soto, I Will review this and add it to master!
