### ISSUE TITLE
Move multicast logic to the PerftestTransport class and add information in the transport summary

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#44]
**TODO**:
- [x] Support for C++ Traditional
- [x] First CR #56
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [x] Documentation
- [ ] Full #56
