### ISSUE TITLE
Add logic in the build scripts to generate the qos_string.h files every time we compile

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#63]
**TODO**:
- [x] Support for build.sh script
- [x] Support for build.bat script
- [x] First CR [Code Review](https://github.com/rticommunity/rtiperftest/pull/88)
- [x] Documentation
- [ ] Full [Code Review](https://github.com/rticommunity/rtiperftest/pull/88)
- [ ] Final Merge into master
