### ISSUE TITLE
Improve RTI Perftest out of the box user experience

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#67]
In order to improve the out of the box user experience we decided to evaluate the following options:

- [x] RTI Version and Perftest version. (#54)
- [x] Show in the summary at the beginning of the test if the test is `latency`/`throughput` and how to run the other. (#46)
- [x] Show in the summary if `reliable`/`best effort`. (#46)
- [x] Use `Batching` for the throughput test by default (#75).
- [x] Evaluate the use of `UDPv4|SHMEM` as the default transport instead of only `UDPv4` (#80).
- [x] Evaluate the use `Best Effort` for the latency test (#79).
- [x] Reduce the Subscriber side size when doing a latency-test. (Initial Samples for Throughput reader) (#74)

**Comment by javmorcas** [comment]
Feedback:

- Latency/Throughput test: If -latencyTest or -ThroughputTest command line parameters are not specified, interactively ask to specify the mode to run and do not default to anything.
- Suggestion: Avoid the need of specifying certain parameters in the subscriber side by using a side channel to communicate all the command line parameters we need. Either by using the user_data of the participant_qos or the announcement topic. This would be needed if we want to default to Best Effort for a Latency Test.
- Enable SHMEM+UDPv4 by default. Test participant creation before hand and if it fails, print a single error explaining the issue.  
- Multicast by default for more than 1 subscriber. This would require suggestion 2.
