### ISSUE TITLE
Use Batching by default when use throughput mode

### ISSUE THREAD

**Issue by alfonso-soto** [rticommunity/rtiperftest#75]
**Description**
 Use Batching for the throughput test by default.

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review](https://github.com/rticommunity/rtiperftest/pull/76)
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [x] Documentation
- [x] Full [Code Review](https://github.com/rticommunity/rtiperftest/pull/76)

**Comment by javmorcas** [comment]
@alfonso-soto Could you go ahead and implement this also in the rest of languages?
