### ISSUE TITLE
Evaluate the use of `UDPv4|SHMEM` by default instead of `UDPv4`

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#80]
Part of:  #67

- In most cases we are going to achieve better performance when using `SHMEM` instead of `UDPv4`.
- Our middleware by default uses SHMEM if available. *RTI Perftest* always use UDPv4 by default.
- In some OS share memory fails by default and RTI ConnextDDS shows an error (OSX for example).
- What about Large Data? We saw issues for huge samples due to the buffer sizes
- What about non-tuned OS where we the shared memory segments are not big enough (related with previous 2 questions).

We want to evaluate if doing such c

** TODO **
 - [x] Evaluate issue
 - [x] Discuss during the performance meeting what to do about this.
- [x] Support for C++ Traditional
- [x] First CR [Code Review](https://github.com/rticommunity/rtiperftest/pull/85)
- [ ] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [x] Documentation
- [x] Full [Code Review](https://github.com/rticommunity/rtiperftest/pull/85)
- [ ] Final Merge into master

**Comment by softwarejimenez** [comment]
I have tested the differences in three different machines and in different scenarios. 
@javmorcas, as you can see in the tables. Whe should use `UDPv4|SHMEM` as default because it is getting better number.

|  Test personal pc |  |  |  |  |  |  |
|  ------ | ------ | ------ | ------ | ------ | ------ | ------ |
|   | 32B |  | 63000B |  | 64000B |  |
|   | UDPv4 | SHMEM | UDPv4 | SHMEM | UDPv4 | SHMEM |
|  Latency test | 14 | 9 | 28 | 22 | 48 | 44 |
|  Throughput test | 787.1 | 837.5 | 18845 | 41130.4 | 12179.7 | 18603.3 |

|  Perf machine |  |  |  |  |  |  |
|  ------ | ------ | ------ | ------ | ------ | ------ | ------ |
|   | 32B |  | 63000B |  | 64000B |  |
|   | UDPv4 | SHMEM | UDPv4 | SHMEM | UDPv4 | SHMEM |
|  Latency test | 23 | 19 | 47 | 37 | 69 | 54 |
|  Throughput test | 619 | 683.7 | 12965.2 | 24061.1 | 9886.2 | 14853.3 |

|  Raspberry Pi machine |  |  |  |  |  |  |
|  ------ | ------ | ------ | ------ | ------ | ------ | ------ |
|   | 32B |  | 63000B |  | 64000B |  |
|   | UDPv4 | SHMEM | UDPv4 | SHMEM | UDPv4 | SHMEM |
|  Latency test | 123 | 96 | 494 | 311 | 788 | 513 |
|  Throughput test | 35.8 | 44.6 | 1097.5 | 2553.2 | 783.2 | 1562.3 |

**Comment by javmorcas** [comment]
The final conclusion for this is that we are moving from `UDPv4` to `UDPv4|SHMEM` for this release.
