### ISSUE TITLE
Include the % of samples lost in the summary of the test

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#81]
Right now we specify the number of samples lost, but not the percentage of packets that represents with respect to the total.

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR #84
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [x] Automatic install testing
- [x] Documentation
- [x] Full #84
