### ISSUE TITLE
Modify RTI Perftest Version to 2.4 and Modify documentation

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#83]
This task should be done right before the release, and after all the rest of the issues are already merged.

**TODO**:
- [x] Support for C++ Traditional
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [x] Documentation
- [x] Full [Code Review]()
