### ISSUE TITLE
Need to promote OS tuning

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#87]
**From Howard**

The tuning of the OS, especially the OS parameters that specify max recv buffer size for Linux is highly important if you want to get the best performance that you can get on a system.
In older version of the documentation, this info was a chapter-level that catches the attention of a person looking at the table of contents (even if it was the last chapter).
In this documentation, the chapter is now a section that doesn't appear in the table of contents nor does it appear in the documentation tree on the left side of the HTML page.
Even knowing that this information must exist, it took me 10 minutes to figure out where it was.
I suggest that this critical information be
1) moved to the front of the Execution chapter. It's currently 5.5.9 of the command line parameters section...and the tuning is certainly not a command line parameter.
2) highlighted as strongly suggest that you optimize your OS and network if you want to achieve the very best performance. And have the section appear both the in the table of contents as well as the document tree in the HTML.
3) can point to other links on the internet that discusses tuning. Here's one that is relevant:
http://fasterdata.es.net/network-tuning/udp-tuning/

**TODO**:
- [x] Discuss issue in Performance meeting
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master
