### ISSUE TITLE
move java_scripts to scripts/java_execution_scripts

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rtiperftest#89]
**Description**

**TODO**:
- [x] Support for build.sh
- [x] Support for build.bat
- [ ] Documentation
- [ ] Full [Code Review]()
- [ ] Final Merge into master
