### ISSUE TITLE
Compilation error in Certain VxWorks

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#93]
**Description**

In certain versions of VxWorks we don't have access to `sys/time.h`, therefore we fail at compilation time when doing the import.

**TODO**:
- [x] Support for C++ Traditional
- [x] Support for C++ Modern
- [ ] Pass [Code Review](https://github.com/rticommunity/rtiperftest/pull/95)
- [ ] Documentation
- [ ] Pull Request #issueNumber
- [ ] Final Merge into master
