### ISSUE TITLE
Provide a way to compile the documentation in srcDoc

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#94]
**Description**

**TODO**:
- [ ] Generate HTML and PDF documentation from the build.sh
- [x] First CR [Code Review](https://github.com/rticommunity/rtiperftest/pull/96)
- [ ] Documentation
- [ ] Full [Code Review](https://github.com/rticommunity/rtiperftest/pull/96)
- [ ] Final Merge into master
