### ISSUE TITLE
Review -multicastAddress option to use 3 different addresses

### ISSUE THREAD

**Issue by javmorcas** [rticommunity/rtiperftest#97]
**Description**

**TODO**:
- [x] Support for C++ Traditional
- [x] First CR [Code Review]()
- [x] Support for C++ Modern
- [x] Support for Java
- [x] Support for CS
- [ ] Automatic install testing
- [x] Documentation
- [x] Full [Code Review]()
- [x] Final Merge into master
